version: '2'
services:
  db:
    image: sqlite3
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
